well_commerce_news:
    configuration:
        news:
            orm:
                factory: WellCommerce\Bundle\NewsBundle\Factory\NewsFactory
                repository: WellCommerce\Bundle\NewsBundle\Repository\NewsRepository
                mapping: "@WellCommerceNewsBundle/Resources/config/doctrine/News.orm.yml"
                entity: WellCommerce\Bundle\NewsBundle\Entity\News
            api:
                exposed: true
                dataset: news.dataset.admin
                manager: news.manager
        news_translation:
            orm:
                manager: false
                mapping: "@WellCommerceNewsBundle/Resources/config/doctrine/NewsTranslation.orm.yml"
                entity: WellCommerce\Bundle\NewsBundle\Entity\NewsTranslation
