
services:
    news.controller.admin:
        class: WellCommerce\Bundle\NewsBundle\Controller\Admin\NewsController
        arguments: ['@news.manager', '@news.form_builder.admin', '@news.datagrid']
        calls:
            - [setContainer, ['@service_container']]

    news.context.front:
        class: WellCommerce\Bundle\NewsBundle\Context\Front\NewsContext
