# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

well_commerce_api:
    request_handler:
        news:
            manager: news.manager
    serialization:
        WellCommerce\Bundle\NewsBundle\Entity\News:
            mapping: "@WellCommerceNewsBundle/Resources/config/serialization/News:.yml"
        WellCommerce\Bundle\NewsBundle\Entity\NewsTranslation:
            mapping: "@WellCommerceNewsBundle/Resources/config/serialization/NewsTranslation:.yml"
